#!/usr/bin/env bash
# Generate the FreeBASIC-NG Homebrew formula from measured release archives.
#
# Every URL, checksum and installation root is derived from a candidate artifact
# that exists on disk.  A formula can therefore not accidentally describe a
# different release than the one whose channel qualification tests it.

set -euo pipefail

readonly PROGRAM='generate-homebrew-formula'

fail() {
  printf '%s: %s\n' "$PROGRAM" "$*" >&2
  exit 1
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d ' ' -f 1
  else
    shasum -a 256 "$1" | cut -d ' ' -f 1
  fi
}

VERSION=''
BASE_URL=''
CANDIDATE_DIR=''
OUTPUT=''

while (($#)); do
  case "$1" in
    --version) VERSION="${2-}"; shift 2 ;;
    --base-url) BASE_URL="${2-}"; shift 2 ;;
    --candidate-dir) CANDIDATE_DIR="${2-}"; shift 2 ;;
    --output) OUTPUT="${2-}"; shift 2 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
  fail '--version must be a three-component release version'
[[ "$BASE_URL" =~ ^https://[^[:space:]?\#]+$ ]] ||
  fail '--base-url must be an HTTPS URL without query or fragment'
[[ -d "$CANDIDATE_DIR" ]] || fail '--candidate-dir is not a directory'
[[ -n "$OUTPUT" ]] || fail '--output is required'
BASE_URL="${BASE_URL%/}"

work=$(mktemp -d "${TMPDIR:-/tmp}/freebasic-ng-formula.XXXXXX")
trap 'rm -rf -- "$work"' EXIT

measure_archive() {
  local target="$1"
  local archive="$CANDIDATE_DIR/freebasic-ng-${VERSION}-${target}.tar.xz"
  local listing="$work/${target}.listing"
  local root="freebasic-ng-${VERSION}-${target}"
  local roots

  [[ -f "$archive" && ! -L "$archive" ]] || fail "candidate is missing $archive"
  tar -tJf "$archive" > "$listing" || fail "$archive is not a readable xz tarball"
  roots=$(sed -n 's#^\([^/]*\)/.*#\1#p' "$listing" | LC_ALL=C sort -u)
  [[ "$roots" == "$root" ]] ||
    fail "$archive must have only top-level directory $root (got: ${roots:-none})"
  for member in "$root/bin/fbc" "$root/include/freebasic" "$root/lib/freebasic/$target"; do
    grep -Eq "^${member}(/|$)" "$listing" || fail "$archive is missing $member"
  done
  printf '%s' "$archive"
}

arm_archive=$(measure_archive darwin-aarch64)
intel_archive=$(measure_archive darwin-x86_64)
arm_sha=$(sha256_of "$arm_archive")
intel_sha=$(sha256_of "$intel_archive")
for digest in "$arm_sha" "$intel_sha"; do
  [[ "$digest" =~ ^[0-9a-f]{64}$ ]] || fail 'measured SHA-256 is malformed'
done

install -d "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<FORMULA
# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class FreebasicNg < Formula
  desc "Modern compiler for the FreeBASIC language"
  homepage "https://github.com/metaneutrons/freebasic-ng"
  license all_of: ["GPL-2.0-or-later", "LGPL-2.1-or-later"]

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE_URL}/$(basename "$arm_archive")"
      sha256 "${arm_sha}"
    elsif Hardware::CPU.intel?
      url "${BASE_URL}/$(basename "$intel_archive")"
      sha256 "${intel_sha}"
    end
  end

  def install
    prefix.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fbc --version")
    source = testpath/"smoke.bas"
    output = testpath/"smoke"
    source.write <<~BASIC
      Print "FreeBASIC-NG package smoke"
    BASIC
    system bin/"fbc", source, "-x", output
    gfx_source = testpath/"gfx-smoke.bas"
    gfx_output = testpath/"gfx-smoke"
    gfx_source.write <<~BASIC
      #include once "fbgfx.bi"
      Dim w As Integer, h As Integer, d As Integer
      ScreenInfo w, h, d
      Print "FreeBASIC-NG graphics smoke"
    BASIC
    system bin/"fbc", "-fbgfx", gfx_source, "-x", gfx_output
    assert_equal "FreeBASIC-NG graphics smoke\\n", shell_output(gfx_output)
    assert_equal "FreeBASIC-NG package smoke\\n", shell_output(output)
  end
end
FORMULA

ruby -c "$OUTPUT" >/dev/null || fail 'generated formula is not valid Ruby'
printf '%s: wrote %s for %s\n' "$PROGRAM" "$OUTPUT" "$VERSION"
