#!/usr/bin/env bash
# Generate the source-built FreeBASIC-NG AUR PKGBUILD from the signed source
# release archive.  The source archive is a release asset, not an unauthenticated
# codeload URL, so its checksum is part of the candidate inventory.

set -euo pipefail

readonly PROGRAM='generate-pkgbuild-source'

fail() {
  printf '%s: %s\n' "$PROGRAM" "$*" >&2
  exit 1
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d ' ' -f 1
  else
    shasum -a 256 "$1" | cut -d ' ' -f 1
  fi
}

VERSION=''
BASE_URL=''
CANDIDATE_DIR=''
OUTPUT=''
while (($#)); do
  case "$1" in
    --version) VERSION="${2-}"; shift 2 ;;
    --base-url) BASE_URL="${2-}"; shift 2 ;;
    --candidate-dir) CANDIDATE_DIR="${2-}"; shift 2 ;;
    --output) OUTPUT="${2-}"; shift 2 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
  fail '--version must be a three-component release version'
[[ "$BASE_URL" =~ ^https://[^[:space:]?\#]+$ ]] ||
  fail '--base-url must be an HTTPS URL without query or fragment'
[[ -d "$CANDIDATE_DIR" ]] || fail '--candidate-dir is not a directory'
[[ -n "$OUTPUT" ]] || fail '--output is required'
BASE_URL="${BASE_URL%/}"

archive="$CANDIDATE_DIR/freebasic-ng-${VERSION}-source.tar.gz"
[[ -f "$archive" && ! -L "$archive" ]] || fail "candidate is missing $archive"
listing=$(mktemp "${TMPDIR:-/tmp}/freebasic-ng-source-listing.XXXXXX")
trap 'rm -f -- "$listing"' EXIT
tar -tzf "$archive" > "$listing" || fail "$archive is not a readable gzip tarball"
mapfile -t roots < <(sed -n 's#^\([^/]*\)/.*#\1#p' "$listing" | LC_ALL=C sort -u)
[[ ${#roots[@]} == 1 ]] || fail 'source archive must contain one top-level directory'
source_root="${roots[0]}"
[[ "$source_root" == "freebasic-ng-${VERSION}" ]] ||
  fail "source archive root must be freebasic-ng-${VERSION}, got $source_root"
for member in CMakeLists.txt LICENSE.md bootstrap/seed-provenance.json \
  scripts/fetch-bootstrap-seed.py; do
  grep -Fxq "$source_root/$member" "$listing" || fail "source archive is missing $member"
done
source_sha=$(sha256_of "$archive")
[[ "$source_sha" =~ ^[0-9a-f]{64}$ ]] || fail 'measured SHA-256 is malformed'

install -d "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<PKGBUILD
# Generated by scripts/release/generate-pkgbuild-source.sh. Do not edit.
# Maintainer: metaneutrons <https://github.com/metaneutrons>
pkgname=freebasic-ng
pkgver=${VERSION}
pkgrel=1
pkgdesc="FreeBASIC-NG compiler"
arch=('x86_64' 'aarch64')
url="https://github.com/metaneutrons/freebasic-ng"
license=('GPL-2.0-or-later' 'LGPL-2.1-or-later')
depends=('gcc' 'binutils' 'ncurses' 'libx11' 'libxext' 'libxpm' 'libxrandr' 'libxrender' 'gpm' 'libffi' 'libglvnd')
makedepends=('ca-certificates' 'cmake' 'ninja' 'python')
# fbc invokes ld directly, so its runtime archives must not contain LTO IR.
options=('!lto' 'staticlibs')
conflicts=('freebasic' 'freebasic-ng-bin')
source=("\$pkgname-\$pkgver.tar.gz::${BASE_URL}/freebasic-ng-${VERSION}-source.tar.gz")
sha256sums=('${source_sha}')

build() {
    cmake -S "${source_root}" -B build -G Ninja \\
        -DCMAKE_BUILD_TYPE=Release -DFB_BUILD_GFXLIB=ON
    cmake --build build
}

check() {
    ./build/src/compiler/fbc --version | grep -F "Version \$pkgver"
    cmake --install build --prefix "\$srcdir/check-stage"
    python "${source_root}/scripts/verify-installed-fbc.py" \\
        --prefix "\$srcdir/check-stage" --expected-host "linux-\$CARCH" --require-gfxlib
}

package() {
    DESTDIR="\$pkgdir" cmake --install build --prefix /usr
    install -Dm644 "${source_root}/LICENSE.md" \\
        "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE.md"
}
PKGBUILD

bash -n "$OUTPUT" || fail 'generated PKGBUILD is not valid shell'
printf '%s: wrote %s for %s\n' "$PROGRAM" "$OUTPUT" "$VERSION"
