#!/usr/bin/env bash
# Generate the binary FreeBASIC-NG AUR PKGBUILD from measured Linux release
# archives.  It never uses SKIP checksums and it ships the release's licensing
# statement from the separately signed source archive.

set -euo pipefail

readonly PROGRAM='generate-pkgbuild-bin'

fail() {
  printf '%s: %s\n' "$PROGRAM" "$*" >&2
  exit 1
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d ' ' -f 1
  else
    shasum -a 256 "$1" | cut -d ' ' -f 1
  fi
}

VERSION=''
BASE_URL=''
CANDIDATE_DIR=''
OUTPUT=''
while (($#)); do
  case "$1" in
    --version) VERSION="${2-}"; shift 2 ;;
    --base-url) BASE_URL="${2-}"; shift 2 ;;
    --candidate-dir) CANDIDATE_DIR="${2-}"; shift 2 ;;
    --output) OUTPUT="${2-}"; shift 2 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
  fail '--version must be a three-component release version'
[[ "$BASE_URL" =~ ^https://[^[:space:]?\#]+$ ]] ||
  fail '--base-url must be an HTTPS URL without query or fragment'
[[ -d "$CANDIDATE_DIR" ]] || fail '--candidate-dir is not a directory'
[[ -n "$OUTPUT" ]] || fail '--output is required'
BASE_URL="${BASE_URL%/}"

work=$(mktemp -d "${TMPDIR:-/tmp}/freebasic-ng-bin-listing.XXXXXX")
trap 'rm -rf -- "$work"' EXIT

measure_binary() {
  local target="$1"
  local archive="$CANDIDATE_DIR/freebasic-ng-${VERSION}-${target}.tar.xz"
  local root="freebasic-ng-${VERSION}-${target}"
  local listing="$work/${target}.listing"
  local roots

  [[ -f "$archive" && ! -L "$archive" ]] || fail "candidate is missing $archive"
  tar -tJf "$archive" > "$listing" || fail "$archive is not a readable xz tarball"
  roots=$(sed -n 's#^\([^/]*\)/.*#\1#p' "$listing" | LC_ALL=C sort -u)
  [[ "$roots" == "$root" ]] || fail "$archive has an unexpected root: ${roots:-none}"
  for member in "$root/bin/fbc" "$root/include/freebasic" "$root/lib/freebasic/$target"; do
    grep -Eq "^${member}(/|$)" "$listing" || fail "$archive is missing $member"
  done
  printf '%s' "$archive"
}

source_archive="$CANDIDATE_DIR/freebasic-ng-${VERSION}-source.tar.gz"
[[ -f "$source_archive" && ! -L "$source_archive" ]] ||
  fail "candidate is missing $source_archive"
source_listing="$work/source.listing"
tar -tzf "$source_archive" > "$source_listing" || fail "$source_archive is not a readable gzip tarball"
grep -Fxq "freebasic-ng-${VERSION}/LICENSE.md" "$source_listing" ||
  fail 'source archive is missing LICENSE.md'

x86_archive=$(measure_binary linux-x86_64)
arm_archive=$(measure_binary linux-aarch64)
x86_sha=$(sha256_of "$x86_archive")
arm_sha=$(sha256_of "$arm_archive")
source_sha=$(sha256_of "$source_archive")
for digest in "$x86_sha" "$arm_sha" "$source_sha"; do
  [[ "$digest" =~ ^[0-9a-f]{64}$ ]] || fail 'measured SHA-256 is malformed'
done

install -d "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<PKGBUILD
# Generated by scripts/release/generate-pkgbuild-bin.sh. Do not edit.
# Maintainer: metaneutrons <https://github.com/metaneutrons>
pkgname=freebasic-ng-bin
pkgver=${VERSION}
pkgrel=1
pkgdesc="FreeBASIC-NG compiler (prebuilt release)"
arch=('x86_64' 'aarch64')
url="https://github.com/metaneutrons/freebasic-ng"
license=('GPL-2.0-or-later' 'LGPL-2.1-or-later')
depends=('gcc' 'binutils' 'ncurses' 'libx11' 'libxext' 'libxpm' 'libxrandr' 'libxrender' 'gpm' 'libffi' 'libglvnd')
options=('staticlibs')
conflicts=('freebasic' 'freebasic-ng')
source=("freebasic-ng-\$pkgver-source.tar.gz::${BASE_URL}/freebasic-ng-${VERSION}-source.tar.gz")
source_x86_64=("freebasic-ng-\$pkgver-linux-x86_64.tar.xz::${BASE_URL}/freebasic-ng-${VERSION}-linux-x86_64.tar.xz")
source_aarch64=("freebasic-ng-\$pkgver-linux-aarch64.tar.xz::${BASE_URL}/freebasic-ng-${VERSION}-linux-aarch64.tar.xz")
sha256sums=('${source_sha}')
sha256sums_x86_64=('${x86_sha}')
sha256sums_aarch64=('${arm_sha}')

package() {
    local target root
    case "\$CARCH" in
        x86_64) target=linux-x86_64 ;;
        aarch64) target=linux-aarch64 ;;
        *) echo "unsupported architecture: \$CARCH" >&2; return 1 ;;
    esac
    root="freebasic-ng-\$pkgver-\$target"
    [[ -x "\$root/bin/fbc" ]] || { echo "missing \$root/bin/fbc" >&2; return 1; }
    install -d "\$pkgdir/usr"
    cp -a "\$root/bin" "\$pkgdir/usr/"
    cp -a "\$root/include" "\$pkgdir/usr/"
    cp -a "\$root/lib" "\$pkgdir/usr/"
    install -Dm644 "freebasic-ng-\$pkgver/LICENSE.md" \\
        "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE.md"
}
PKGBUILD

bash -n "$OUTPUT" || fail 'generated PKGBUILD is not valid shell'
printf '%s: wrote %s for %s\n' "$PROGRAM" "$OUTPUT" "$VERSION"
